name: Release
on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: ver
        shell: pwsh
        run: |
          $v = (Import-PowerShellDataFile -Path src/TrayVBox.version.psd1).Version
          "version=$v" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Install Inno Setup & PSScriptAnalyzer
        shell: pwsh
        run: |
          choco install innosetup -y
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force -AllowClobber

      - name: Build
        shell: pwsh
        run: |
          ./scripts/build.ps1 -Release

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TrayVBox-${{ steps.ver.outputs.version }}-Setup.exe
          name: TrayVBox v${{ steps.ver.outputs.version }}
          generate_release_notes: true